### ISSUE TITLE
Some emojis are not displayed full.

### ISSUE THREAD

**Issue by LampPrinter** [mr-pennyworth/alfred-fastest-emoji#3]
<img width="554" alt="Screenshot 2021-08-06 at 2 16 35 PM" src="https://user-images.githubusercontent.com/7559328/128483946-879826f5-9a70-4231-9914-ae0ad86560d2.png">

<img width="554" alt="Screenshot 2021-08-06 at 2 16 49 PM" src="https://user-images.githubusercontent.com/7559328/128484002-244c08ee-e573-42ee-acf1-77934a3907b3.png">

**Comment by mr-pennyworth** [comment]
@LampPrinter apologies for such a late response!

I'm not able to reproduce the issue with my setup:
<img width="562" alt="image" src="https://github.com/mr-pennyworth/alfred-fastest-emoji/assets/74945464/883f40d7-e32b-4a06-9778-8614e91e996f">

As was the case with a previous issue (#1), maybe the issue is that icons weren't correctly generated?
The following would help me figure out the cause and fix it:
- Does the issue exist with the latest release?
- If the issue exists, can you download the joypixels version and see if the problem exists?
- The icons are not displayed, what about the emoji itself? When you press enter, does the correct emoji get pasted?
